///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BVT_Admin_Wenapp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Create_admin_role recording.
    /// </summary>
    [TestModule("d0abf0e2-3bd1-4cda-8098-254bb105b3bf", ModuleType.Recording, 1)]
    public partial class Create_admin_role : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BVT_Admin_WebappRepository repository.
        /// </summary>
        public static BVT_Admin_WebappRepository repo = BVT_Admin_WebappRepository.Instance;

        static Create_admin_role instance = new Create_admin_role();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Create_admin_role()
        {
            New_user = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Create_admin_role Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable url.
        /// </summary>
        [TestVariable("0349e901-4169-4b6d-8d82-bb2facc1de58")]
        public string url
        {
            get { return repo.url; }
            set { repo.url = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable New_user.
        /// </summary>
        [TestVariable("a09d2004-1918-4389-9eaf-d6f5e440a01a")]
        public string New_user
        {
            get { return repo.New_user; }
            set { repo.New_user = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.ManageRoles' at Center.", repo.AdminWebapp.ManageRolesInfo, new RecordItemIndex(0));
            repo.AdminWebapp.ManageRoles.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.CREATENEWROLE' at Center.", repo.AdminWebapp.Root.CREATENEWROLEInfo, new RecordItemIndex(1));
            repo.AdminWebapp.Root.CREATENEWROLE.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ADMIN' with focus on 'AdminWebapp.Root.DeviceType1'.", repo.AdminWebapp.Root.DeviceType1Info, new RecordItemIndex(2));
            repo.AdminWebapp.Root.DeviceType1.PressKeys("ADMIN");
            Delay.Milliseconds(0);
            
            New_user = Ranorex_Automation_Helpers.UserCodeCollections.Pentair_random_data.getRandomEmail();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$New_user' with focus on 'AdminWebapp.Root.Type'.", repo.AdminWebapp.Root.TypeInfo, new RecordItemIndex(4));
            repo.AdminWebapp.Root.Type.PressKeys(New_user);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Ranorex_Automated_user' with focus on 'AdminWebapp.Root.Type1'.", repo.AdminWebapp.Root.Type1Info, new RecordItemIndex(5));
            repo.AdminWebapp.Root.Type1.PressKeys("Ranorex_Automated_user");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.RadioCustomLabel2' at Center.", repo.AdminWebapp.Root.RadioCustomLabel2Info, new RecordItemIndex(6));
            repo.AdminWebapp.Root.RadioCustomLabel2.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.RadioCustomLabel1' at Center.", repo.AdminWebapp.Root.RadioCustomLabel1Info, new RecordItemIndex(7));
            repo.AdminWebapp.Root.RadioCustomLabel1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.RadioCustomLabel3' at Center.", repo.AdminWebapp.Root.RadioCustomLabel3Info, new RecordItemIndex(8));
            repo.AdminWebapp.Root.RadioCustomLabel3.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.RadioCustomLabelRadioCustomTrue1' at Center.", repo.AdminWebapp.Root.RadioCustomLabelRadioCustomTrue1Info, new RecordItemIndex(9));
            repo.AdminWebapp.Root.RadioCustomLabelRadioCustomTrue1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.RadioCustomLabel4' at Center.", repo.AdminWebapp.Root.RadioCustomLabel4Info, new RecordItemIndex(10));
            repo.AdminWebapp.Root.RadioCustomLabel4.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.RadioCustomLabel5' at Center.", repo.AdminWebapp.Root.RadioCustomLabel5Info, new RecordItemIndex(11));
            repo.AdminWebapp.Root.RadioCustomLabel5.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.RadioCustomLabel6' at Center.", repo.AdminWebapp.Root.RadioCustomLabel6Info, new RecordItemIndex(12));
            repo.AdminWebapp.Root.RadioCustomLabel6.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.RadioCustomLabel7' at Center.", repo.AdminWebapp.Root.RadioCustomLabel7Info, new RecordItemIndex(13));
            repo.AdminWebapp.Root.RadioCustomLabel7.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.RadioCustomLabel8' at Center.", repo.AdminWebapp.Root.RadioCustomLabel8Info, new RecordItemIndex(14));
            repo.AdminWebapp.Root.RadioCustomLabel8.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.RadioCustomLabel9' at Center.", repo.AdminWebapp.Root.RadioCustomLabel9Info, new RecordItemIndex(15));
            repo.AdminWebapp.Root.RadioCustomLabel9.Click();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(16));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.CREATEROLE' at Center.", repo.AdminWebapp.Root.CREATEROLEInfo, new RecordItemIndex(17));
            repo.AdminWebapp.Root.CREATEROLE.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='span') on item 'AdminWebapp1.Root.CreateNewRole'.", repo.AdminWebapp1.Root.CreateNewRoleInfo, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.CreateNewRoleInfo, "TagName", "span");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='div') on item 'AdminWebapp1.Root.ButtonClassRow'.", repo.AdminWebapp1.Root.ButtonClassRowInfo, new RecordItemIndex(19));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.ButtonClassRowInfo, "TagName", "div");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='div') on item 'AdminWebapp1.Root.RoleTypeBox4'.", repo.AdminWebapp1.Root.RoleTypeBox4Info, new RecordItemIndex(20));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.RoleTypeBox4Info, "TagName", "div");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='div') on item 'AdminWebapp1.Root.RoleTypeBox3'.", repo.AdminWebapp1.Root.RoleTypeBox3Info, new RecordItemIndex(21));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.RoleTypeBox3Info, "TagName", "div");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='div') on item 'AdminWebapp1.Root.RoleTypeBox2'.", repo.AdminWebapp1.Root.RoleTypeBox2Info, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.RoleTypeBox2Info, "TagName", "div");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='div') on item 'AdminWebapp1.Root.RoleTypeBox1'.", repo.AdminWebapp1.Root.RoleTypeBox1Info, new RecordItemIndex(23));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.RoleTypeBox1Info, "TagName", "div");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='div') on item 'AdminWebapp1.Root.RoleTypeBox'.", repo.AdminWebapp1.Root.RoleTypeBoxInfo, new RecordItemIndex(24));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.RoleTypeBoxInfo, "TagName", "div");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 8s.", new RecordItemIndex(25));
            Delay.Duration(8000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(26));
            
            Report.Log(ReportLevel.Info, "User", New_user, new RecordItemIndex(27));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.New_Admin_Support' at Center.", repo.AdminWebapp.Root.New_Admin_SupportInfo, new RecordItemIndex(28));
            repo.AdminWebapp.Root.New_Admin_Support.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(29));
            Delay.Duration(3000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(30));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.Edit' at Center.", repo.AdminWebapp.Root.EditInfo, new RecordItemIndex(31));
            repo.AdminWebapp.Root.Edit.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.RadioCustomLabelRadioCustomTrue1' at Center.", repo.AdminWebapp.Root.RadioCustomLabelRadioCustomTrue1Info, new RecordItemIndex(32));
            repo.AdminWebapp.Root.RadioCustomLabelRadioCustomTrue1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.UPDATEROLE' at Center.", repo.AdminWebapp.Root.UPDATEROLEInfo, new RecordItemIndex(33));
            repo.AdminWebapp.Root.UPDATEROLE.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(34));
            Delay.Duration(3000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(35));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Confirm' at Center.", repo.AdminWebapp.ConfirmInfo, new RecordItemIndex(36));
            repo.AdminWebapp.Confirm.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(37));
            Delay.Duration(4000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(38));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
