///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BVT_Admin_Wenapp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Create_support_role recording.
    /// </summary>
    [TestModule("ad67f524-41aa-43df-961c-9238ac0a31d6", ModuleType.Recording, 1)]
    public partial class Create_support_role : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BVT_Admin_WebappRepository repository.
        /// </summary>
        public static BVT_Admin_WebappRepository repo = BVT_Admin_WebappRepository.Instance;

        static Create_support_role instance = new Create_support_role();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Create_support_role()
        {
            New_user = "";
            New_support_admin = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Create_support_role Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable url.
        /// </summary>
        [TestVariable("0349e901-4169-4b6d-8d82-bb2facc1de58")]
        public string url
        {
            get { return repo.url; }
            set { repo.url = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable New_user.
        /// </summary>
        [TestVariable("76b875db-f07e-463d-84a6-db4b43fa9bf8")]
        public string New_user
        {
            get { return repo.New_user; }
            set { repo.New_user = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable New_support_admin.
        /// </summary>
        [TestVariable("297ab19e-0605-4e52-8f1a-6d31815c9a24")]
        public string New_support_admin
        {
            get { return repo.New_support_admin; }
            set { repo.New_support_admin = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.ManageRoles' at Center.", repo.AdminWebapp.ManageRolesInfo, new RecordItemIndex(0));
            repo.AdminWebapp.ManageRoles.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.CREATENEWROLE' at Center.", repo.AdminWebapp.Root.CREATENEWROLEInfo, new RecordItemIndex(1));
            repo.AdminWebapp.Root.CREATENEWROLE.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'SUPPORT' with focus on 'AdminWebapp.Root.DeviceType1'.", repo.AdminWebapp.Root.DeviceType1Info, new RecordItemIndex(2));
            repo.AdminWebapp.Root.DeviceType1.PressKeys("SUPPORT");
            Delay.Milliseconds(0);
            
            New_user = Ranorex_Automation_Helpers.UserCodeCollections.Pentair_random_data.getRandomEmail();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$New_user' with focus on 'AdminWebapp.Root.Type'.", repo.AdminWebapp.Root.TypeInfo, new RecordItemIndex(4));
            repo.AdminWebapp.Root.Type.PressKeys(New_user);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Ranorex_Automated_user' with focus on 'AdminWebapp.Root.Type1'.", repo.AdminWebapp.Root.Type1Info, new RecordItemIndex(5));
            repo.AdminWebapp.Root.Type1.PressKeys("Ranorex_Automated_user");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='span') on item 'AdminWebapp1.Root.CreateNewRole'.", repo.AdminWebapp1.Root.CreateNewRoleInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.CreateNewRoleInfo, "TagName", "span");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.RadioCustomLabelRadioCustomTrue' at Center.", repo.AdminWebapp.Root.RadioCustomLabelRadioCustomTrueInfo, new RecordItemIndex(7));
            repo.AdminWebapp.Root.RadioCustomLabelRadioCustomTrue.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.RadioCustomLabel1' at Center.", repo.AdminWebapp.Root.RadioCustomLabel1Info, new RecordItemIndex(8));
            repo.AdminWebapp.Root.RadioCustomLabel1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='span') on item 'AdminWebapp1.Root.CreateNewRole1'.", repo.AdminWebapp1.Root.CreateNewRole1Info, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.CreateNewRole1Info, "TagName", "span");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='div') on item 'AdminWebapp1.Root.ColMd12ColSm12NoPaddingNoRight'.", repo.AdminWebapp1.Root.ColMd12ColSm12NoPaddingNoRightInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.ColMd12ColSm12NoPaddingNoRightInfo, "TagName", "div");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='div') on item 'AdminWebapp1.Root.PanelBody5'.", repo.AdminWebapp1.Root.PanelBody5Info, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.PanelBody5Info, "TagName", "div");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='div') on item 'AdminWebapp1.Root.FormGroup3'.", repo.AdminWebapp1.Root.FormGroup3Info, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.FormGroup3Info, "TagName", "div");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(13));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.CREATEROLE' at Center.", repo.AdminWebapp.Root.CREATEROLEInfo, new RecordItemIndex(14));
            repo.AdminWebapp.Root.CREATEROLE.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 8s.", new RecordItemIndex(15));
            Delay.Duration(8000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(16));
            
            Report.Log(ReportLevel.Info, "User", New_user, new RecordItemIndex(17));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.New_Admin_Support' at Center.", repo.AdminWebapp.Root.New_Admin_SupportInfo, new RecordItemIndex(18));
            repo.AdminWebapp.Root.New_Admin_Support.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(19));
            Delay.Duration(3000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(20));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.Edit' at Center.", repo.AdminWebapp.Root.EditInfo, new RecordItemIndex(21));
            repo.AdminWebapp.Root.Edit.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.RadioCustomLabel' at Center.", repo.AdminWebapp.Root.RadioCustomLabelInfo, new RecordItemIndex(22));
            repo.AdminWebapp.Root.RadioCustomLabel.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.UPDATEROLE' at Center.", repo.AdminWebapp.Root.UPDATEROLEInfo, new RecordItemIndex(23));
            repo.AdminWebapp.Root.UPDATEROLE.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(24));
            Delay.Duration(3000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(25));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Confirm' at Center.", repo.AdminWebapp.ConfirmInfo, new RecordItemIndex(26));
            repo.AdminWebapp.Confirm.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(27));
            Delay.Duration(4000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(28));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='span') on item 'AdminWebapp1.Root.ManageRoles'.", repo.AdminWebapp1.Root.ManageRolesInfo, new RecordItemIndex(29));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.ManageRolesInfo, "TagName", "span");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
