///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BVT_Admin_Wenapp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The manage_certificates recording.
    /// </summary>
    [TestModule("9e10b177-5a7a-4dcc-9486-9867e9c25072", ModuleType.Recording, 1)]
    public partial class manage_certificates : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BVT_Admin_WebappRepository repository.
        /// </summary>
        public static BVT_Admin_WebappRepository repo = BVT_Admin_WebappRepository.Instance;

        static manage_certificates instance = new manage_certificates();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public manage_certificates()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static manage_certificates Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable url.
        /// </summary>
        [TestVariable("0349e901-4169-4b6d-8d82-bb2facc1de58")]
        public string url
        {
            get { return repo.url; }
            set { repo.url = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Certificate' at Center.", repo.AdminWebapp.CertificateInfo, new RecordItemIndex(0));
            repo.AdminWebapp.Certificate.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(1));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='span') on item 'AdminWebapp1.Root.ManageCertificate'.", repo.AdminWebapp1.Root.ManageCertificateInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.ManageCertificateInfo, "TagName", "span");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='span') on item 'AdminWebapp1.Root.CertificatesTemplates'.", repo.AdminWebapp1.Root.CertificatesTemplatesInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.CertificatesTemplatesInfo, "TagName", "span");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='button') on item 'AdminWebapp1.Root.CREATEOTACODESIGNINGPROFILE'.", repo.AdminWebapp1.Root.CREATEOTACODESIGNINGPROFILEInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.CREATEOTACODESIGNINGPROFILEInfo, "TagName", "button");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='span') on item 'AdminWebapp1.Root.AddCertificateTemplates'.", repo.AdminWebapp1.Root.AddCertificateTemplatesInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.AddCertificateTemplatesInfo, "TagName", "span");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='span') on item 'AdminWebapp1.Root.DownloadCertificate'.", repo.AdminWebapp1.Root.DownloadCertificateInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.DownloadCertificateInfo, "TagName", "span");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='span') on item 'AdminWebapp1.Root.DeviceType'.", repo.AdminWebapp1.Root.DeviceTypeInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.DeviceTypeInfo, "TagName", "span");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='span') on item 'AdminWebapp1.Root.DownloadTemplate'.", repo.AdminWebapp1.Root.DownloadTemplateInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.DownloadTemplateInfo, "TagName", "span");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='span') on item 'AdminWebapp1.Root.Delete'.", repo.AdminWebapp1.Root.DeleteInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.DeleteInfo, "TagName", "span");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='img') on item 'AdminWebapp1.Root.Remove'.", repo.AdminWebapp1.Root.RemoveInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.RemoveInfo, "TagName", "img");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='div') on item 'AdminWebapp1.Root.ColMd6ColSm12NoLeftPadding'.", repo.AdminWebapp1.Root.ColMd6ColSm12NoLeftPaddingInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.ColMd6ColSm12NoLeftPaddingInfo, "TagName", "div");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.Download1' at Center.", repo.AdminWebapp.Root.Download1Info, new RecordItemIndex(12));
            repo.AdminWebapp.Root.Download1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(13));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.Download2' at Center.", repo.AdminWebapp.Root.Download2Info, new RecordItemIndex(14));
            repo.AdminWebapp.Root.Download2.Click();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(15));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.CREATEOTACODESIGNINGPROFILE' at Center.", repo.AdminWebapp.Root.CREATEOTACODESIGNINGPROFILEInfo, new RecordItemIndex(16));
            repo.AdminWebapp.Root.CREATEOTACODESIGNINGPROFILE.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 6s.", new RecordItemIndex(17));
            Delay.Duration(6000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.Download1' at Center.", repo.AdminWebapp.Root.Download1Info, new RecordItemIndex(18));
            repo.AdminWebapp.Root.Download1.Click();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(19));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
