///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BVT_Admin_Wenapp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The View_parameters recording.
    /// </summary>
    [TestModule("cff0c8be-ea23-4dc1-b5b3-82558ee54559", ModuleType.Recording, 1)]
    public partial class View_parameters : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BVT_Admin_WebappRepository repository.
        /// </summary>
        public static BVT_Admin_WebappRepository repo = BVT_Admin_WebappRepository.Instance;

        static View_parameters instance = new View_parameters();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public View_parameters()
        {
            PIF0 = "";
            ESC1 = "";
            XTR1 = "";
            SSS1 = "";
            WQM1 = "";
            SSPC1 = "";
            PIDO = "";
            PPA0 = "";
            PPS0 = "";
            PGW0 = "";
            PLC1 = "";
            SSS = "";
            IF3 = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static View_parameters Instance
        {
            get { return instance; }
        }

#region Variables

        string _PIF0;

        /// <summary>
        /// Gets or sets the value of variable PIF0.
        /// </summary>
        [TestVariable("2a05bc19-55c2-483c-86c7-2206555774fc")]
        public string PIF0
        {
            get { return _PIF0; }
            set { _PIF0 = value; }
        }

        string _ESC1;

        /// <summary>
        /// Gets or sets the value of variable ESC1.
        /// </summary>
        [TestVariable("9392b7c0-00d9-48d2-af98-a86ab12ebf4c")]
        public string ESC1
        {
            get { return _ESC1; }
            set { _ESC1 = value; }
        }

        string _XTR1;

        /// <summary>
        /// Gets or sets the value of variable XTR1.
        /// </summary>
        [TestVariable("a569a4fb-80fd-422b-8cef-9a7d0be25753")]
        public string XTR1
        {
            get { return _XTR1; }
            set { _XTR1 = value; }
        }

        string _SSS1;

        /// <summary>
        /// Gets or sets the value of variable SSS1.
        /// </summary>
        [TestVariable("aeb43b2d-1747-4113-9840-df4f5b4d7ec2")]
        public string SSS1
        {
            get { return _SSS1; }
            set { _SSS1 = value; }
        }

        string _WQM1;

        /// <summary>
        /// Gets or sets the value of variable WQM1.
        /// </summary>
        [TestVariable("09fe9c8f-eeb3-45b2-88aa-47e8555a1aad")]
        public string WQM1
        {
            get { return _WQM1; }
            set { _WQM1 = value; }
        }

        string _SSPC1;

        /// <summary>
        /// Gets or sets the value of variable SSPC1.
        /// </summary>
        [TestVariable("f370a1b3-981d-4ca2-b611-1290fbea5a42")]
        public string SSPC1
        {
            get { return _SSPC1; }
            set { _SSPC1 = value; }
        }

        string _PIDO;

        /// <summary>
        /// Gets or sets the value of variable PIDO.
        /// </summary>
        [TestVariable("e5667e95-4a30-4509-86e4-19f060d565cc")]
        public string PIDO
        {
            get { return _PIDO; }
            set { _PIDO = value; }
        }

        string _PPA0;

        /// <summary>
        /// Gets or sets the value of variable PPA0.
        /// </summary>
        [TestVariable("cf69b277-b1d9-4568-9719-39927b7d71df")]
        public string PPA0
        {
            get { return _PPA0; }
            set { _PPA0 = value; }
        }

        string _PPS0;

        /// <summary>
        /// Gets or sets the value of variable PPS0.
        /// </summary>
        [TestVariable("b11dd0c1-09c7-48a8-9b65-a3cbdcfe6836")]
        public string PPS0
        {
            get { return _PPS0; }
            set { _PPS0 = value; }
        }

        string _PGW0;

        /// <summary>
        /// Gets or sets the value of variable PGW0.
        /// </summary>
        [TestVariable("bae9c079-906f-4d81-aba9-881dec1016cc")]
        public string PGW0
        {
            get { return _PGW0; }
            set { _PGW0 = value; }
        }

        string _PLC1;

        /// <summary>
        /// Gets or sets the value of variable PLC1.
        /// </summary>
        [TestVariable("0457598b-42c0-4542-983b-8b68136c8c01")]
        public string PLC1
        {
            get { return _PLC1; }
            set { _PLC1 = value; }
        }

        string _SSS;

        /// <summary>
        /// Gets or sets the value of variable SSS.
        /// </summary>
        [TestVariable("b54a43bd-0410-4538-9301-8db8bb6376f1")]
        public string SSS
        {
            get { return _SSS; }
            set { _SSS = value; }
        }

        string _IF3;

        /// <summary>
        /// Gets or sets the value of variable IF3.
        /// </summary>
        [TestVariable("69422fd2-4a85-4ebe-afaa-1388be341698")]
        public string IF3
        {
            get { return _IF3; }
            set { _IF3 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable url.
        /// </summary>
        [TestVariable("0349e901-4169-4b6d-8d82-bb2facc1de58")]
        public string url
        {
            get { return repo.url; }
            set { repo.url = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.ManageDevices' at Center.", repo.AdminWebapp.ManageDevicesInfo, new RecordItemIndex(0));
            repo.AdminWebapp.ManageDevices.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDropdown' at Center.", repo.AdminWebapp.SearchMenuDropdownInfo, new RecordItemIndex(1));
            repo.AdminWebapp.SearchMenuDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(2));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDeviceID' at Center.", repo.AdminWebapp.SearchMenuDeviceIDInfo, new RecordItemIndex(3));
            repo.AdminWebapp.SearchMenuDeviceID.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$XTR1' with focus on 'AdminWebapp.Root.Text'.", repo.AdminWebapp.Root.TextInfo, new RecordItemIndex(4));
            repo.AdminWebapp.Root.Text.PressKeys(XTR1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(5));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(6));
            Delay.Duration(4000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ViewParameters' at Center.", repo.AdminWebapp.Root.ViewParametersInfo, new RecordItemIndex(8));
            repo.AdminWebapp.Root.ViewParameters.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 8s.", new RecordItemIndex(9));
            Delay.Duration(8000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Attribute ID') on item 'AdminWebapp.Root.AttributeID'.", repo.AdminWebapp.Root.AttributeIDInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.AdminWebapp.Root.AttributeIDInfo, "InnerText", "Attribute ID");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ManageDevices' at Center.", repo.AdminWebapp.Root.ManageDevicesInfo, new RecordItemIndex(12));
            repo.AdminWebapp.Root.ManageDevices.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDropdown' at Center.", repo.AdminWebapp.SearchMenuDropdownInfo, new RecordItemIndex(13));
            repo.AdminWebapp.SearchMenuDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(14));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDeviceID' at Center.", repo.AdminWebapp.SearchMenuDeviceIDInfo, new RecordItemIndex(15));
            repo.AdminWebapp.SearchMenuDeviceID.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ESC1' with focus on 'AdminWebapp.Root.Text'.", repo.AdminWebapp.Root.TextInfo, new RecordItemIndex(16));
            repo.AdminWebapp.Root.Text.PressKeys(ESC1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(17));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(18));
            Delay.Duration(4000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(19));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ViewParameters' at Center.", repo.AdminWebapp.Root.ViewParametersInfo, new RecordItemIndex(20));
            repo.AdminWebapp.Root.ViewParameters.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 8s.", new RecordItemIndex(21));
            Delay.Duration(8000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Attribute ID') on item 'AdminWebapp.Root.AttributeID'.", repo.AdminWebapp.Root.AttributeIDInfo, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.AdminWebapp.Root.AttributeIDInfo, "InnerText", "Attribute ID");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(23));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ManageDevices' at Center.", repo.AdminWebapp.Root.ManageDevicesInfo, new RecordItemIndex(24));
            repo.AdminWebapp.Root.ManageDevices.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDropdown' at Center.", repo.AdminWebapp.SearchMenuDropdownInfo, new RecordItemIndex(25));
            repo.AdminWebapp.SearchMenuDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(26));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDeviceID' at Center.", repo.AdminWebapp.SearchMenuDeviceIDInfo, new RecordItemIndex(27));
            repo.AdminWebapp.SearchMenuDeviceID.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$PIF0' with focus on 'AdminWebapp.Root.Text'.", repo.AdminWebapp.Root.TextInfo, new RecordItemIndex(28));
            repo.AdminWebapp.Root.Text.PressKeys(PIF0);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(29));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(30));
            Delay.Duration(4000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(31));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ViewParameters' at Center.", repo.AdminWebapp.Root.ViewParametersInfo, new RecordItemIndex(32));
            repo.AdminWebapp.Root.ViewParameters.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 8s.", new RecordItemIndex(33));
            Delay.Duration(8000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Attribute ID') on item 'AdminWebapp.Root.AttributeID'.", repo.AdminWebapp.Root.AttributeIDInfo, new RecordItemIndex(34));
            Validate.AttributeEqual(repo.AdminWebapp.Root.AttributeIDInfo, "InnerText", "Attribute ID");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(35));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ManageDevices' at Center.", repo.AdminWebapp.Root.ManageDevicesInfo, new RecordItemIndex(36));
            repo.AdminWebapp.Root.ManageDevices.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDropdown' at Center.", repo.AdminWebapp.SearchMenuDropdownInfo, new RecordItemIndex(37));
            repo.AdminWebapp.SearchMenuDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(38));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDeviceID' at Center.", repo.AdminWebapp.SearchMenuDeviceIDInfo, new RecordItemIndex(39));
            repo.AdminWebapp.SearchMenuDeviceID.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$WQM1' with focus on 'AdminWebapp.Root.Text'.", repo.AdminWebapp.Root.TextInfo, new RecordItemIndex(40));
            repo.AdminWebapp.Root.Text.PressKeys(WQM1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(41));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(42));
            Delay.Duration(4000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(43));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ViewParameters' at Center.", repo.AdminWebapp.Root.ViewParametersInfo, new RecordItemIndex(44));
            repo.AdminWebapp.Root.ViewParameters.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 8s.", new RecordItemIndex(45));
            Delay.Duration(8000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Attribute ID') on item 'AdminWebapp.Root.AttributeID'.", repo.AdminWebapp.Root.AttributeIDInfo, new RecordItemIndex(46));
            Validate.AttributeEqual(repo.AdminWebapp.Root.AttributeIDInfo, "InnerText", "Attribute ID");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(47));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ManageDevices' at Center.", repo.AdminWebapp.Root.ManageDevicesInfo, new RecordItemIndex(48));
            repo.AdminWebapp.Root.ManageDevices.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDropdown' at Center.", repo.AdminWebapp.SearchMenuDropdownInfo, new RecordItemIndex(49));
            repo.AdminWebapp.SearchMenuDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(50));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDeviceID' at Center.", repo.AdminWebapp.SearchMenuDeviceIDInfo, new RecordItemIndex(51));
            repo.AdminWebapp.SearchMenuDeviceID.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$SSPC1' with focus on 'AdminWebapp.Root.Text'.", repo.AdminWebapp.Root.TextInfo, new RecordItemIndex(52));
            repo.AdminWebapp.Root.Text.PressKeys(SSPC1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(53));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(54));
            Delay.Duration(4000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(55));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ViewParameters' at Center.", repo.AdminWebapp.Root.ViewParametersInfo, new RecordItemIndex(56));
            repo.AdminWebapp.Root.ViewParameters.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 8s.", new RecordItemIndex(57));
            Delay.Duration(8000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Attribute ID') on item 'AdminWebapp.Root.AttributeID'.", repo.AdminWebapp.Root.AttributeIDInfo, new RecordItemIndex(58));
            Validate.AttributeEqual(repo.AdminWebapp.Root.AttributeIDInfo, "InnerText", "Attribute ID");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(59));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ManageDevices' at Center.", repo.AdminWebapp.Root.ManageDevicesInfo, new RecordItemIndex(60));
            repo.AdminWebapp.Root.ManageDevices.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDropdown' at Center.", repo.AdminWebapp.SearchMenuDropdownInfo, new RecordItemIndex(61));
            repo.AdminWebapp.SearchMenuDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(62));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDeviceID' at Center.", repo.AdminWebapp.SearchMenuDeviceIDInfo, new RecordItemIndex(63));
            repo.AdminWebapp.SearchMenuDeviceID.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$PIDO' with focus on 'AdminWebapp.Root.Text'.", repo.AdminWebapp.Root.TextInfo, new RecordItemIndex(64));
            repo.AdminWebapp.Root.Text.PressKeys(PIDO);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(65));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(66));
            Delay.Duration(4000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(67));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ViewParameters' at Center.", repo.AdminWebapp.Root.ViewParametersInfo, new RecordItemIndex(68));
            repo.AdminWebapp.Root.ViewParameters.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 8s.", new RecordItemIndex(69));
            Delay.Duration(8000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Attribute ID') on item 'AdminWebapp.Root.AttributeID'.", repo.AdminWebapp.Root.AttributeIDInfo, new RecordItemIndex(70));
            Validate.AttributeEqual(repo.AdminWebapp.Root.AttributeIDInfo, "InnerText", "Attribute ID");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(71));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ManageDevices' at Center.", repo.AdminWebapp.Root.ManageDevicesInfo, new RecordItemIndex(72));
            repo.AdminWebapp.Root.ManageDevices.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDropdown' at Center.", repo.AdminWebapp.SearchMenuDropdownInfo, new RecordItemIndex(73));
            repo.AdminWebapp.SearchMenuDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(74));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDeviceID' at Center.", repo.AdminWebapp.SearchMenuDeviceIDInfo, new RecordItemIndex(75));
            repo.AdminWebapp.SearchMenuDeviceID.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$PPA0' with focus on 'AdminWebapp.Root.Text'.", repo.AdminWebapp.Root.TextInfo, new RecordItemIndex(76));
            repo.AdminWebapp.Root.Text.PressKeys(PPA0);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(77));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(78));
            Delay.Duration(4000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(79));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ViewParameters' at Center.", repo.AdminWebapp.Root.ViewParametersInfo, new RecordItemIndex(80));
            repo.AdminWebapp.Root.ViewParameters.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 8s.", new RecordItemIndex(81));
            Delay.Duration(8000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Attribute ID') on item 'AdminWebapp.Root.AttributeID'.", repo.AdminWebapp.Root.AttributeIDInfo, new RecordItemIndex(82));
            Validate.AttributeEqual(repo.AdminWebapp.Root.AttributeIDInfo, "InnerText", "Attribute ID");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(83));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ManageDevices' at Center.", repo.AdminWebapp.Root.ManageDevicesInfo, new RecordItemIndex(84));
            repo.AdminWebapp.Root.ManageDevices.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDropdown' at Center.", repo.AdminWebapp.SearchMenuDropdownInfo, new RecordItemIndex(85));
            repo.AdminWebapp.SearchMenuDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(86));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDeviceID' at Center.", repo.AdminWebapp.SearchMenuDeviceIDInfo, new RecordItemIndex(87));
            repo.AdminWebapp.SearchMenuDeviceID.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$PPS0' with focus on 'AdminWebapp.Root.Text'.", repo.AdminWebapp.Root.TextInfo, new RecordItemIndex(88));
            repo.AdminWebapp.Root.Text.PressKeys(PPS0);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(89));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(90));
            Delay.Duration(4000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(91));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ViewParameters' at Center.", repo.AdminWebapp.Root.ViewParametersInfo, new RecordItemIndex(92));
            repo.AdminWebapp.Root.ViewParameters.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 8s.", new RecordItemIndex(93));
            Delay.Duration(8000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Attribute ID') on item 'AdminWebapp.Root.AttributeID'.", repo.AdminWebapp.Root.AttributeIDInfo, new RecordItemIndex(94));
            Validate.AttributeEqual(repo.AdminWebapp.Root.AttributeIDInfo, "InnerText", "Attribute ID");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(95));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ManageDevices' at Center.", repo.AdminWebapp.Root.ManageDevicesInfo, new RecordItemIndex(96));
            repo.AdminWebapp.Root.ManageDevices.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDropdown' at Center.", repo.AdminWebapp.SearchMenuDropdownInfo, new RecordItemIndex(97));
            repo.AdminWebapp.SearchMenuDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(98));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDeviceID' at Center.", repo.AdminWebapp.SearchMenuDeviceIDInfo, new RecordItemIndex(99));
            repo.AdminWebapp.SearchMenuDeviceID.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$PGW0' with focus on 'AdminWebapp.Root.Text'.", repo.AdminWebapp.Root.TextInfo, new RecordItemIndex(100));
            repo.AdminWebapp.Root.Text.PressKeys(PGW0);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(101));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(102));
            Delay.Duration(4000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(103));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ViewParameters' at Center.", repo.AdminWebapp.Root.ViewParametersInfo, new RecordItemIndex(104));
            repo.AdminWebapp.Root.ViewParameters.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 8s.", new RecordItemIndex(105));
            Delay.Duration(8000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Attribute ID') on item 'AdminWebapp.Root.AttributeID'.", repo.AdminWebapp.Root.AttributeIDInfo, new RecordItemIndex(106));
            Validate.AttributeEqual(repo.AdminWebapp.Root.AttributeIDInfo, "InnerText", "Attribute ID");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(107));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ManageDevices' at Center.", repo.AdminWebapp.Root.ManageDevicesInfo, new RecordItemIndex(108));
            repo.AdminWebapp.Root.ManageDevices.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDropdown' at Center.", repo.AdminWebapp.SearchMenuDropdownInfo, new RecordItemIndex(109));
            repo.AdminWebapp.SearchMenuDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(110));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDeviceID' at Center.", repo.AdminWebapp.SearchMenuDeviceIDInfo, new RecordItemIndex(111));
            repo.AdminWebapp.SearchMenuDeviceID.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$PLC1' with focus on 'AdminWebapp.Root.Text'.", repo.AdminWebapp.Root.TextInfo, new RecordItemIndex(112));
            repo.AdminWebapp.Root.Text.PressKeys(PLC1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(113));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(114));
            Delay.Duration(4000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(115));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ViewParameters' at Center.", repo.AdminWebapp.Root.ViewParametersInfo, new RecordItemIndex(116));
            repo.AdminWebapp.Root.ViewParameters.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 8s.", new RecordItemIndex(117));
            Delay.Duration(8000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Attribute ID') on item 'AdminWebapp.Root.AttributeID'.", repo.AdminWebapp.Root.AttributeIDInfo, new RecordItemIndex(118));
            Validate.AttributeEqual(repo.AdminWebapp.Root.AttributeIDInfo, "InnerText", "Attribute ID");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(119));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ManageDevices' at Center.", repo.AdminWebapp.Root.ManageDevicesInfo, new RecordItemIndex(120));
            repo.AdminWebapp.Root.ManageDevices.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDropdown' at Center.", repo.AdminWebapp.SearchMenuDropdownInfo, new RecordItemIndex(121));
            repo.AdminWebapp.SearchMenuDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(122));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDeviceID' at Center.", repo.AdminWebapp.SearchMenuDeviceIDInfo, new RecordItemIndex(123));
            repo.AdminWebapp.SearchMenuDeviceID.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$SSS' with focus on 'AdminWebapp.Root.Text'.", repo.AdminWebapp.Root.TextInfo, new RecordItemIndex(124));
            repo.AdminWebapp.Root.Text.PressKeys(SSS);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(125));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(126));
            Delay.Duration(4000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(127));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ViewParameters' at Center.", repo.AdminWebapp.Root.ViewParametersInfo, new RecordItemIndex(128));
            repo.AdminWebapp.Root.ViewParameters.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 8s.", new RecordItemIndex(129));
            Delay.Duration(8000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Attribute ID') on item 'AdminWebapp.Root.AttributeID'.", repo.AdminWebapp.Root.AttributeIDInfo, new RecordItemIndex(130));
            Validate.AttributeEqual(repo.AdminWebapp.Root.AttributeIDInfo, "InnerText", "Attribute ID");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(131));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ManageDevices' at Center.", repo.AdminWebapp.Root.ManageDevicesInfo, new RecordItemIndex(132));
            repo.AdminWebapp.Root.ManageDevices.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDropdown' at Center.", repo.AdminWebapp.SearchMenuDropdownInfo, new RecordItemIndex(133));
            repo.AdminWebapp.SearchMenuDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(134));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.SearchMenuDeviceID' at Center.", repo.AdminWebapp.SearchMenuDeviceIDInfo, new RecordItemIndex(135));
            repo.AdminWebapp.SearchMenuDeviceID.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$IF3' with focus on 'AdminWebapp.Root.Text'.", repo.AdminWebapp.Root.TextInfo, new RecordItemIndex(136));
            repo.AdminWebapp.Root.Text.PressKeys(IF3);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(137));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(138));
            Delay.Duration(4000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(139));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminWebapp.Root.ViewParameters' at Center.", repo.AdminWebapp.Root.ViewParametersInfo, new RecordItemIndex(140));
            repo.AdminWebapp.Root.ViewParameters.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 8s.", new RecordItemIndex(141));
            Delay.Duration(8000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Attribute ID') on item 'AdminWebapp.Root.AttributeID'.", repo.AdminWebapp.Root.AttributeIDInfo, new RecordItemIndex(142));
            Validate.AttributeEqual(repo.AdminWebapp.Root.AttributeIDInfo, "InnerText", "Attribute ID");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdminWebapp.Screenshots, false, new RecordItemIndex(143));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='div') on item 'AdminWebapp1.Root.BreadcrumbWraper'.", repo.AdminWebapp1.Root.BreadcrumbWraperInfo, new RecordItemIndex(144));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.BreadcrumbWraperInfo, "TagName", "div");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='h4') on item 'AdminWebapp1.Root.DevicesParameters'.", repo.AdminWebapp1.Root.DevicesParametersInfo, new RecordItemIndex(145));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.DevicesParametersInfo, "TagName", "h4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='div') on item 'AdminWebapp1.Root.ColMd10NegatineTopMarginNoLeftPa'.", repo.AdminWebapp1.Root.ColMd10NegatineTopMarginNoLeftPaInfo, new RecordItemIndex(146));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.ColMd10NegatineTopMarginNoLeftPaInfo, "TagName", "div");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='span') on item 'AdminWebapp1.Root.AttributeID'.", repo.AdminWebapp1.Root.AttributeIDInfo, new RecordItemIndex(147));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.AttributeIDInfo, "TagName", "span");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='span') on item 'AdminWebapp1.Root.AttributeName'.", repo.AdminWebapp1.Root.AttributeNameInfo, new RecordItemIndex(148));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.AttributeNameInfo, "TagName", "span");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='span') on item 'AdminWebapp1.Root.Value'.", repo.AdminWebapp1.Root.ValueInfo, new RecordItemIndex(149));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.ValueInfo, "TagName", "span");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='span') on item 'AdminWebapp1.Root.Units'.", repo.AdminWebapp1.Root.UnitsInfo, new RecordItemIndex(150));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.UnitsInfo, "TagName", "span");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='span') on item 'AdminWebapp1.Root.TimeStamp'.", repo.AdminWebapp1.Root.TimeStampInfo, new RecordItemIndex(151));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.TimeStampInfo, "TagName", "span");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='img') on item 'AdminWebapp1.Root.ExportAll'.", repo.AdminWebapp1.Root.ExportAllInfo, new RecordItemIndex(152));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.ExportAllInfo, "TagName", "img");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='div') on item 'AdminWebapp1.Root.TableResponsive'.", repo.AdminWebapp1.Root.TableResponsiveInfo, new RecordItemIndex(153));
            Validate.AttributeEqual(repo.AdminWebapp1.Root.TableResponsiveInfo, "TagName", "div");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
